<?php

include('header.php');
require __DIR__ . '/../vendor/autoload.php';
use chillerlan\QRCode\QRCode;

?>
<div class='container cont'>
<ol class="breadcrumb">
				<li><a href="/">Home</a></li>
				<li><a class='active' >preregistration</a></li>
				
	</ol>

<h2>
    Generated code: <?=$code?>
</h2>
<center><img src='<?php echo (new QRCode())->render($code);?>'></center>
<br>
<h3>
<p>This is the code generated by our systems after your registration.</p>
<p>Remember to save this code in order to show it to the healthcare personnel</p>
<p><strong>Important!!!</strong> We sent the <strong>qrcode</strong> connected to this code to your email. If you haven't received it yet check the spam folder.</p>
</h3>

</div>


<?php include('footer.php'); ?>
